version: "3"
services:
  ldapserver:
    container_name: ldapserver
    image: openfrontier/apacheds:latest
    ports:
      - 389:10389

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.1
    ports:
      - "4000:8080"
    environment:
      KEYCLOAK_ADMIN: admin 
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: 
      - start-dev

volumes:
  db:

networks:
  default:
    name: backend
    external: true